### ISSUE TITLE
Vias

### ISSUE THREAD

**Issue by ghost** [themaninthesuitcase/kicad_delete_tracks_plugin#1]
Maybe consider deleting unlocked vias as well?

**Comment by themaninthesuitcase** [comment]
It already does the vias!

The right track is locked, as is the bottom via.

Before:
<img width="350" alt="Screenshot 2022-05-22 at 21 06 15" src="https://user-images.githubusercontent.com/196630/169713809-758ad965-1bf5-423e-a9cf-12231c143eff.png">

After:
<img width="350" alt="Screenshot 2022-05-22 at 21 06 28" src="https://user-images.githubusercontent.com/196630/169713819-f63291e6-c1e1-4855-9f21-f202faf68ac2.png">

For some reason vias are actually a track, or more accurately inherit from track:
<img width="290" alt="Screenshot 2022-05-22 at 21 10 07" src="https://user-images.githubusercontent.com/196630/169713912-41c12efd-1ebc-44db-be2a-5ff9febc83e2.png">
